const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const APP_REV="REV_07";
const SCHEMA_VERSION=7;
const STORAGE_KEY="zpd_word_state";
const LEGACY_KEYS=["zpd_rev06_state"];
const DEFAULT_WORDS=[
{id:"w1",eng:"environment",kor:"환경",example:"We should protect the environment.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w2",eng:"evidence",kor:"증거",example:"The detective found new evidence.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w3",eng:"responsible",kor:"책임이 있는",example:"She is responsible for the task.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w4",eng:"maintain",kor:"유지하다",example:"It is hard to maintain focus.",wrong:1,pass:0,hint:0,learningStats:{}},
{id:"w5",eng:"present",kor:"현재의",example:"Focus on the present moment.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w6",eng:"essential",kor:"필수적인",example:"Sleep is essential for health.",wrong:2,pass:0,hint:0,learningStats:{}},
{id:"w7",eng:"approach",kor:"접근하다",example:"We need a new approach.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w8",eng:"challenge",kor:"도전",example:"This word is a good challenge.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w9",eng:"consider",kor:"고려하다",example:"Consider every clue.",wrong:0,pass:0,hint:0,learningStats:{}},
{id:"w10",eng:"benefit",kor:"이익, 혜택",example:"Practice has many benefits.",wrong:0,pass:0,hint:0,learningStats:{}}
];
const GUIDE_OPTIONS=[
{id:"fox",label:"호기심 많은 여우",img:"./assets/characters/guide_default.png",style:"curious",tone:"궁금한 친구"},
{id:"rabbit",label:"느긋한 토끼",img:"./assets/characters/rabbit.png",style:"calm",tone:"느긋한 친구"},
{id:"raccoon",label:"장난 많은 친구",img:"./assets/characters/sloth.png",style:"play",tone:"장난 많은 친구"},
{id:"cat",label:"은근히 시크한 친구",img:"./assets/characters/fennec.png",style:"chic",tone:"은근히 시크한 친구"}
];
const NAME_BANK=["포레","루나","모카","리오","코코","민트","클로버","아루","루미","가온","토리","라온"];
const nowISO=()=>new Date().toISOString();
const today=()=>nowISO().slice(0,10);
const clone=x=>JSON.parse(JSON.stringify(x));
const DEFAULT_STATE={
 schemaVersion:SCHEMA_VERSION,appRevision:APP_REV,
 profile:{displayName:"",avatarMode:"default",avatarAssetRef:"",createdAt:"",updatedAt:""},
 guide:{id:"fox",name:"",style:"curious",voice:true},
 settings:{sound:true,partnerVoice:true,reducedMotion:false,pressureReduced:false,geminiModel:"gemini-2.5-flash"},
 sheets:[{sheetId:"sample",title:"이번 주 시험",createdAt:nowISO(),updatedAt:nowISO(),testDate:"",sourceType:"sample",sourceCount:0,status:"LEARNING",caseMastery:0,items:clone(DEFAULT_WORDS),recognitionMeta:{}}],
 activeSheetId:"sample",sessions:[],xp:0,streak:0,lastStudy:"",memory:{},ocrDraft:null,
 learning:{phase:"first",firstIndex:0,meaningIndex:0,connectionRound:0,weakRound:0,combo:0,flow:0,fever:false,history:[]},
 codeRed:{index:0,results:{},history:[],retrace:[],retryOnly:false,targetIds:[]},
 onboardingStep:0,onboardingDone:false
};
function normalizeWord(w,i=0){return {id:w.id||`w-${Date.now()}-${i}`,eng:String(w.eng||"").trim(),kor:String(w.kor||"").trim(),example:w.example||"",wrong:Number(w.wrong||0),pass:Number(w.pass||0),hint:Number(w.hint||0),confidence:w.confidence||"high",needsReview:!!w.needsReview,manuallyEdited:!!w.manuallyEdited,learningStats:w.learningStats||{}}}
function migrate(raw){
 const s=Object.assign(clone(DEFAULT_STATE),raw||{});
 s.schemaVersion=SCHEMA_VERSION;s.appRevision=APP_REV;
 s.profile=Object.assign({},DEFAULT_STATE.profile,raw?.profile||{});s.guide=Object.assign({},DEFAULT_STATE.guide,raw?.guide||{});s.settings=Object.assign({},DEFAULT_STATE.settings,raw?.settings||{});
 s.learning=Object.assign({},DEFAULT_STATE.learning,raw?.learning||raw?.study||{});s.codeRed=Object.assign({},DEFAULT_STATE.codeRed,raw?.codeRed||{});s.memory=raw?.memory||{};
 if(!Array.isArray(s.sheets)||!s.sheets.length)s.sheets=clone(DEFAULT_STATE.sheets);
 s.sheets=s.sheets.map((sh,si)=>({...sh,sheetId:sh.sheetId||`sheet-${si}`,updatedAt:sh.updatedAt||sh.createdAt||nowISO(),status:sh.status||"READY",caseMastery:Number(sh.caseMastery||0),items:(sh.items||[]).map(normalizeWord),recognitionMeta:sh.recognitionMeta||{}}));
 if(!s.sheets.find(x=>x.sheetId===s.activeSheetId))s.activeSheetId=s.sheets[0].sheetId;
 return s;
}
function load(){
 try{let raw=localStorage.getItem(STORAGE_KEY);if(!raw){for(const k of LEGACY_KEYS){raw=localStorage.getItem(k);if(raw)break}}return raw?migrate(JSON.parse(raw)):clone(DEFAULT_STATE)}catch{return clone(DEFAULT_STATE)}
}
let S=load(),currentTab="home",viewStack=[],runtimeApiKey=sessionStorage.getItem("zpd_runtime_api_key")||"",selectedGuide=S.guide.id||"fox",selectedGuideName=S.guide.name||"",selectedProfileFile=null,selectedTile=null,codeSession=null,codeTimer=null,selectedKey=null,toastTimer=null;
function save(){S.schemaVersion=SCHEMA_VERSION;S.appRevision=APP_REV;localStorage.setItem(STORAGE_KEY,JSON.stringify(S))}
function sheet(){return S.sheets.find(x=>x.sheetId===S.activeSheetId)||S.sheets[0]}
function validWords(){return (sheet()?.items||[]).filter(w=>w.eng&&w.kor&&!w.needsReview)}
function allWords(){return sheet()?.items||[]}
function esc(v=""){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function shuffle(a){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function toast(msg){const t=$("#toast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove("show"),1900)}
function guideAsset(mood="default"){const m={default:"guide_default",smile:"guide_smile",think:"guide_think",play:"guide_play",focus:"guide_focus",cheer:"guide_cheer",hint:"guide_hint",note:"guide_note",radio:"guide_radio",fever:"guide_fever"}[mood]||"guide_default";return `./assets/characters/${m}.png`}
function setPartner(msg,mood="default",speakIt=false){const text=$("#partnerText"),name=$("#partnerName"),img=$("#partnerAvatar");if(text)text.textContent=msg;if(name)name.textContent=S.guide.name||"나의 길잡이";if(img)img.src=guideAsset(mood);if(speakIt)partnerSpeak(msg)}
function partnerSpeak(text=$("#partnerText")?.textContent||""){if(!S.settings.partnerVoice||!S.guide.voice||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ko-KR";u.rate=.96;speechSynthesis.speak(u)}
function speakWord(word){if(!("speechSynthesis" in window))return toast("이 기기에서는 음성 기능을 사용할 수 없어요.");speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang="en-US";u.rate=.82;speechSynthesis.speak(u)}
function markStudy(xp=2){const d=today();if(S.lastStudy!==d){S.streak=S.lastStudy?S.streak+1:1;S.lastStudy=d;S.sessions.push({date:d,count:0})}const r=S.sessions.find(x=>x.date===d);if(r)r.count++;S.xp+=xp;save()}
function memoryStrength(){const ws=validWords();if(!ws.length)return 0;return Math.round(ws.reduce((a,w)=>a+(S.memory[w.id]?.strength??Math.max(25,100-(w.wrong||0)*18-(w.pass||0)*10)),0)/ws.length)}
function learningProgress(){const ws=validWords();if(!ws.length)return 0;const p={first:15,meaning:42,connection:68,weak:82,code:90,done:100}[S.learning.phase]||0;return p}
function stateLabel(st){return ({DRAFT:"초안",REVIEW_REQUIRED:"확인 필요",READY:"학습 준비",LEARNING:"학습 중",CODE_RED_READY:"CODE RED 준비",RETRACE_REQUIRED:"재추적",TEST_READY:"시험 준비 완료",COMPLETED:"완료",ARCHIVED:"보관"})[st]||st}
function weakScore(w){return (w.wrong||0)*5+(w.pass||0)*4+(w.hint||0)*3+(w.learningStats?.slowCorrect||0)}
function updateChrome(){const onboard=!S.onboardingDone;$("#bottomNav").style.display=onboard?"none":"grid";$("#partnerBar").style.display=onboard?"none":"flex";$("#settingsBtn").style.visibility=onboard?"hidden":"visible";$("#backBtn").hidden=viewStack.length===0;$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===currentTab))}
function pushView(fn){viewStack.push(()=>render());fn();updateChrome()}
function goBack(){const fn=viewStack.pop();stopCodeTimer();if(fn)fn();else render();updateChrome()}
function render(){stopCodeTimer();updateChrome();if(!S.onboardingDone)return renderOnboarding();const map={home:renderHome,sheets:renderSheets,study:renderLearningHub,words:renderWords,records:renderRecords};(map[currentTab]||renderHome)();updateChrome()}
async function dbOpen(){return new Promise((res,rej)=>{const q=indexedDB.open("zpd-word-assets",1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains("assets"))q.result.createObjectStore("assets")};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function dbSet(k,v){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction("assets","readwrite");tx.objectStore("assets").put(v,k);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function dbGet(k){const db=await dbOpen();return new Promise((res,rej)=>{const q=db.transaction("assets").objectStore("assets").get(k);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function avatarURL(){if(S.profile.avatarMode!=="illustrated")return "";try{const blob=await dbGet("profile-avatar");return blob?URL.createObjectURL(blob):""}catch{return ""}}
async function stylizePhoto(file){const bmp=await createImageBitmap(file,{imageOrientation:"from-image"});const low=256,size=512,c=document.createElement("canvas"),small=document.createElement("canvas");small.width=low;small.height=low;const sctx=small.getContext("2d",{willReadFrequently:true}),scale=Math.max(low/bmp.width,low/bmp.height),w=bmp.width*scale,h=bmp.height*scale;sctx.filter="saturate(1.16) contrast(1.06) brightness(1.05)";sctx.drawImage(bmp,(low-w)/2,(low-h)/2,w,h);const data=sctx.getImageData(0,0,low,low),px=data.data,step=34;for(let i=0;i<px.length;i+=4){px[i]=Math.round(px[i]/step)*step;px[i+1]=Math.round(px[i+1]/step)*step;px[i+2]=Math.round(px[i+2]/step)*step}sctx.putImageData(data,0,0);c.width=size;c.height=size;const ctx=c.getContext("2d");ctx.imageSmoothingQuality="high";ctx.drawImage(small,0,0,size,size);ctx.globalCompositeOperation="soft-light";ctx.fillStyle="rgba(184,220,164,.22)";ctx.fillRect(0,0,size,size);ctx.globalCompositeOperation="source-over";return new Promise(r=>c.toBlob(r,"image/webp",.9))}
function renderOnboarding(){
 const step=S.onboardingStep||0,dots=`<div class="step-dots">${[0,1,2,3].map(i=>`<i class="${i<=step?"on":""}"></i>`).join("")}</div>`;
 if(step===0)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>탐험가, 반가워!</h1><p>사용자와 길잡이는 서로 다른 존재야. 먼저 네 이름부터 정해볼까?</p></div><section class="card tint-leaf"><label>사용자 이름</label><input id="profileName" class="input" maxlength="20" value="${esc(S.profile.displayName)}" placeholder="이름을 입력해 주세요"><div class="section-title"><h2>빠른 선택</h2><span>언제든 변경 가능</span></div><div class="name-chip-row">${["지우","서윤","도윤","예준"].map(n=>`<button class="name-chip" data-profile-name="${n}" type="button">${n}</button>`).join("")}</div><div class="btn-row" style="margin-top:16px"><button class="btn secondary" data-skip-all type="button">나중에 하기</button><button class="btn primary" id="nextProfileName" type="button">다음</button></div></section></section>`;
 if(step===1)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>내 ZPD 프로필</h1><p>사진은 선택 사항이야. 원본은 장기 저장하지 않아.</p></div><section class="card tint-sky"><div class="photo-preview" id="photoPreview"><span>사진 선택</span></div><div class="btn-row"><button class="btn secondary" id="profileCameraBtn" type="button">사진 찍기</button><button class="btn secondary" id="profileLibraryBtn" type="button">앨범에서 선택</button></div><p style="margin-top:11px">선택한 이미지는 기기 안에서 프로필용 톤으로 변환하며, 확정 결과만 IndexedDB에 저장합니다.</p><div class="btn-row" style="margin-top:16px"><button class="btn secondary" data-next="2" type="button">나중에 하기</button><button class="btn primary" id="confirmAvatar" type="button">계속</button></div></section></section>`;
 if(step===2)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>나의 수사 동료</h1><p>능력은 모두 같아. 취향과 애착만 고르면 돼.</p></div><div class="guide-grid">${GUIDE_OPTIONS.map(g=>`<button class="guide-card ${selectedGuide===g.id?"selected":""}" data-guide="${g.id}" type="button"><img src="${g.img}" alt=""><b>${g.label}</b><small>${g.tone}</small></button>`).join("")}</div><div class="btn-row" style="margin-top:16px"><button class="btn secondary" data-next="3" type="button">나중에 정하기</button><button class="btn primary" data-next="3" type="button">같이 갈래?</button></div></section>`;
 if(step===3)$("#view").innerHTML=`<section class="onboard"><div class="onboard-head">${dots}<h1>이름을 지어줄까?</h1><p>추천받거나 직접 입력할 수 있어.</p></div><section class="card"><div class="partner-mini"><img src="${guideAsset("smile")}" alt=""><div><b>${GUIDE_OPTIONS.find(x=>x.id===selectedGuide)?.label||"나의 길잡이"}</b><p>학습 기능은 어떤 이름을 골라도 같아.</p></div></div><div class="section-title"><h2>이름 추천</h2><button class="btn secondary" id="rerollNames" type="button">다시 추천</button></div><div class="name-chip-row">${shuffle(NAME_BANK).slice(0,5).map(n=>`<button class="name-chip ${selectedGuideName===n?"selected":""}" data-guide-name="${n}" type="button">${n}</button>`).join("")}</div><div class="section-title"><h2>직접 입력</h2></div><input id="guideNameInput" class="input" maxlength="16" value="${esc(selectedGuideName)}" placeholder="길잡이 이름"><div class="btn-row" style="margin-top:16px"><button class="btn secondary" id="finishNoGuideName" type="button">나중에 정하기</button><button class="btn primary" id="finishOnboarding" type="button">동행 시작</button></div></section></section>`;
 bindOnboarding();updateChrome()
}
function bindOnboarding(){
 $$('[data-profile-name]').forEach(b=>b.onclick=()=>{$('#profileName').value=b.dataset.profileName});
 $('#nextProfileName')?.addEventListener('click',()=>{const n=$('#profileName').value.trim();if(!n)return toast('이름을 입력해 주세요.');S.profile.displayName=n;S.profile.updatedAt=nowISO();S.onboardingStep=1;save();render()});
 $('[data-skip-all]')?.addEventListener('click',()=>finishOnboard());$$('[data-next]').forEach(b=>b.onclick=()=>{S.onboardingStep=Number(b.dataset.next);save();render()});
 $('#profileCameraBtn')?.addEventListener('click',()=>$('#profileCameraInput').click());$('#profileLibraryBtn')?.addEventListener('click',()=>$('#profileLibraryInput').click());
 $$('[data-guide]').forEach(b=>b.onclick=()=>{selectedGuide=b.dataset.guide;renderOnboarding()});$('#rerollNames')?.addEventListener('click',()=>{selectedGuideName='';renderOnboarding()});
 $$('[data-guide-name]').forEach(b=>b.onclick=()=>{selectedGuideName=b.dataset.guideName;$('#guideNameInput').value=selectedGuideName;$$('[data-guide-name]').forEach(x=>x.classList.toggle('selected',x===b))});
 $('#finishNoGuideName')?.addEventListener('click',()=>finishOnboard(''));$('#finishOnboarding')?.addEventListener('click',()=>finishOnboard($('#guideNameInput').value.trim()));
 $('#confirmAvatar')?.addEventListener('click',async()=>{if(selectedProfileFile){const blob=await stylizePhoto(selectedProfileFile);await dbSet('profile-avatar',blob);S.profile.avatarMode='illustrated';S.profile.avatarAssetRef='indexeddb:profile-avatar'}S.onboardingStep=2;save();render()});
}
async function profilePicked(file){if(!file||!file.type.startsWith('image/'))return toast('이미지 파일을 선택해 주세요.');selectedProfileFile=file;const blob=await stylizePhoto(file),url=URL.createObjectURL(blob),box=$('#photoPreview');if(box)box.innerHTML=`<img src="${url}" alt="프로필 미리보기">`}
function finishOnboard(name=selectedGuideName){S.guide.id=selectedGuide;S.guide.name=name||'길잡이';S.guide.style=GUIDE_OPTIONS.find(x=>x.id===selectedGuide)?.style||'curious';S.onboardingDone=true;S.onboardingStep=4;S.profile.createdAt=S.profile.createdAt||nowISO();save();currentTab='home';viewStack=[];render();setPartner(`${S.profile.displayName||'탐험가'}, 새 사건이 들어왔어. 시험지부터 볼까?`,'smile')}
async function renderHome(){
 const av=await avatarURL(),sh=sheet(),ws=validWords(),weak=ws.filter(w=>weakScore(w)>0).length,progress=learningProgress(),remain=Math.max(0,ws.length-Object.keys(S.codeRed.results||{}).length),first=(S.profile.displayName||'나').slice(0,1);
 $('#view').innerHTML=`<section class="world-hero"><div class="hero-profile"><div class="user-chip">${av?`<img class="avatar-circle" src="${av}" alt="사용자 프로필">`:`<div class="avatar-circle avatar-fallback">${esc(first)}</div>`}<div><b>${esc(S.profile.displayName||'탐험가')}</b><small>Lv.${Math.floor(S.xp/100)+1} · ${S.xp} XP</small></div></div><img class="guide-peek" src="${guideAsset('smile')}" alt="${esc(S.guide.name||'길잡이')}"></div><div class="hero-case"><div class="hero-kicker"><span>ACTIVE CASE</span><span>${stateLabel(sh.status)}</span></div><h1>${esc(sh.title)}</h1><p>${ws.length}단어 · 취약 ${weak}개 · CODE RED 남은 ${remain}개</p><div class="progress" style="margin-top:8px"><span style="width:${progress}%"></span></div><div class="hero-actions"><button class="btn primary" id="photoFirst" type="button">사진으로 시험지 만들기</button><button class="btn secondary" id="continueCase" type="button">이어하기</button></div></div></section>
 <section class="primary-intake"><div><h2>새 시험지 접수</h2><p>카메라 또는 사진 보관함 → OCR SEE/PAIR → 확인 → 저장 순서로 진행합니다.</p><div class="btn-row" style="margin-top:10px"><button class="btn dark" id="homeCamera" type="button">카메라</button><button class="btn secondary" id="homeLibrary" type="button">사진 보관함</button></div></div><img class="intake-illustration" src="${guideAsset('note')}" alt=""></section>
 <div class="section-title"><h2>오늘의 수사 상태</h2><span>Case Mastery ≠ Memory Strength</span></div><section class="status-strip"><div class="status-pill"><b>${sh.caseMastery||0}%</b><span>Case Mastery</span></div><div class="status-pill"><b>${memoryStrength()}%</b><span>Memory</span></div><div class="status-pill"><b>${S.streak}일</b><span>연속 학습</span></div></section>
 <div class="section-title"><h2>나의 수사 동료</h2><span>기능 차등 없음</span></div><section class="card tint-sky"><div class="partner-mini"><img src="${guideAsset('default')}" alt=""><div><b>${esc(S.guide.name||'길잡이')}</b><p>${GUIDE_OPTIONS.find(x=>x.id===S.guide.id)?.label||'나의 수사 동료'} · ${GUIDE_OPTIONS.find(x=>x.id===S.guide.id)?.tone||''}</p></div></div></section>`;
 $('#photoFirst').onclick=()=>{$('#sheetCameraInput').click()};$('#homeCamera').onclick=()=>$('#sheetCameraInput').click();$('#homeLibrary').onclick=()=>$('#sheetLibraryInput').click();$('#continueCase').onclick=()=>{currentTab='study';render()};setPartner('새 시험지가 최우선이야. 준비됐으면 사진부터 접수하자.','default')
}
function renderSheets(){
 $('#view').innerHTML=`<div class="section-title"><h2>시험지 · 사건 파일</h2><span>Camera First</span></div><section class="primary-intake"><div><h2>새 시험지 만들기</h2><p>사진 결과는 바로 저장하지 않고 확인 화면을 반드시 거칩니다.</p><div class="btn-row" style="margin-top:10px"><button class="btn primary" id="cameraSheet" type="button">카메라로 찍기</button><button class="btn secondary" id="librarySheet" type="button">사진 보관함</button></div></div><img class="intake-illustration" src="${guideAsset('focus')}" alt=""></section><div class="section-title"><h2>사건 파일</h2><span>${S.sheets.length}개</span></div>${S.sheets.map(sh=>`<section class="card" style="margin-bottom:8px"><div class="hero-kicker"><span>${stateLabel(sh.status)}</span><span>${(sh.items||[]).filter(w=>!w.needsReview).length}단어</span></div><h3>${esc(sh.title)}</h3><div class="progress" style="margin:10px 0"><span style="width:${sh.caseMastery||0}%"></span></div><div class="btn-row"><button class="btn secondary open-sheet" data-id="${esc(sh.sheetId)}" type="button">열기</button><button class="btn secondary review-sheet" data-id="${esc(sh.sheetId)}" type="button">단어 확인</button></div></section>`).join('')}`;
 $('#cameraSheet').onclick=()=>$('#sheetCameraInput').click();$('#librarySheet').onclick=()=>$('#sheetLibraryInput').click();$$('.open-sheet').forEach(b=>b.onclick=()=>{S.activeSheetId=b.dataset.id;save();currentTab='study';render()});$$('.review-sheet').forEach(b=>b.onclick=()=>{S.activeSheetId=b.dataset.id;save();renderOCRReview(allWords(),false)});setPartner('시험지는 설정에 숨기지 않아. 여기서 바로 열고 확인할 수 있어.','note')
}
async function preflightImage(file){
 if(!file||file.size<=0)throw new Error('빈 파일이에요.');if(!/^image\//.test(file.type||''))throw new Error('이미지 파일을 선택해 주세요.');if(file.size>20*1024*1024)throw new Error('사진이 너무 커요. 20MB 이하 사진을 사용해 주세요.');
 let bmp;try{bmp=await createImageBitmap(file,{imageOrientation:'from-image'})}catch{throw new Error('사진을 열 수 없어요. 다른 사진으로 다시 시도해 주세요.')}
 const short=Math.min(bmp.width,bmp.height),long=Math.max(bmp.width,bmp.height),warnings=[];if(short<700)warnings.push('해상도가 낮아요');if(long<1200)warnings.push('글자가 작게 보일 수 있어요');const ratio=long/Math.max(1,short);if(ratio>4.5)warnings.push('사진 비율이 너무 길어요');return {width:bmp.width,height:bmp.height,warnings,quality:warnings.length?'확인 필요':'양호'}
}
async function sheetPicked(file){
 try{const q=await preflightImage(file),url=URL.createObjectURL(file);pushView(()=>{$('#view').innerHTML=`<section class="card tint-leaf"><div class="hero-kicker"><span>SOURCE SELECT</span><span>${q.quality}</span></div><h2>증거 사진 접수</h2><p>시험지 전체와 글자가 선명하게 보이는지 확인해 주세요.</p><div class="sheet-shot" style="margin-top:12px"><img src="${url}" alt="시험지 사진 미리보기"><div class="scan-frame"></div></div><div class="quality-grid"><div class="quality-chip"><b>${q.width}×${q.height}</b>해상도</div><div class="quality-chip"><b>${Math.round(file.size/1024)}KB</b>파일</div><div class="quality-chip"><b>${q.quality}</b>품질</div></div>${q.warnings.length?`<p style="margin-top:10px">확인: ${esc(q.warnings.join(' · '))}</p>`:''}<div class="btn-row" style="margin-top:12px"><button class="btn secondary" id="replaceShot" type="button">다른 사진</button><button class="btn primary" id="analyzeShot" type="button">OCR 분석</button></div></section>`;$('#replaceShot').onclick=()=>$('#sheetLibraryInput').click();$('#analyzeShot').onclick=()=>analyzeSheet(file,q);setPartner(q.warnings.length?'단서가 조금 약해 보여. 그래도 분석할 수는 있지만 결과 확인은 꼭 해줘.':'좋아, 글씨가 꽤 또렷해. 이 정도면 수사 가능.','focus')})}catch(e){toast(e.message||'사진을 확인할 수 없어요.')}
}
async function normalizedImageBase64(file,maxLong=2400){const bmp=await createImageBitmap(file,{imageOrientation:'from-image'}),scale=Math.min(1,maxLong/Math.max(bmp.width,bmp.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bmp.width*scale));c.height=Math.max(1,Math.round(bmp.height*scale));const ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(bmp,0,0,c.width,c.height);const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.9));return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res({b64:String(fr.result).split(',')[1],mime:'image/jpeg'});fr.onerror=()=>rej(fr.error);fr.readAsDataURL(blob)})}
async function analyzeSheet(file,quality){
 if(!navigator.onLine)return toast('OCR 분석은 온라인 연결이 필요해요. 저장된 학습은 오프라인에서도 사용할 수 있습니다.');
 if(!runtimeApiKey){return pushView(()=>renderManualEntry('API Key가 없어 OCR을 실행하지 않았어요. 직접 입력은 사용할 수 있습니다.'))}
 $('#view').innerHTML=`<section class="card"><div class="hero-kicker"><span>OCR</span><span>Draft only</span></div><h2>단어 흔적 찾는 중</h2><p id="ocrStage">SEE · 사진에 실제 보이는 문자열 확인 중</p><div class="progress" style="margin-top:16px"><span id="ocrProgress" style="width:24%"></span></div></section>`;setPartner('먼저 보이는 글자를 읽고, 그다음 단어와 뜻의 짝을 확인할게.','note',true);
 try{const img=await normalizedImageBase64(file),seePrompt=`사진에 실제로 보이는 영어 단어와 한글 뜻만 행 순서대로 전사하세요. 원본에 없는 단어를 만들지 말고, 예문/힌트/정답 추측을 하지 마세요. 불확실하면 confidence를 low로 표시하세요. JSON만 출력: {"rows":[{"eng":"...","kor":"...","confidence":"high|medium|low"}]}`,see=await gemini(seePrompt,img.b64,img.mime);$('#ocrStage').textContent='PAIR · 영어 단어와 한국어 뜻 대응 확인 중';$('#ocrProgress').style.width='66%';const pairPrompt=`아래 SEE OCR 행만 사용해 영어 단어-한국어 뜻의 짝을 검증하세요. 원본에 없는 새 단어를 만들지 마세요. 헤더/번호/잡음은 제외하고 원래 순서를 유지하세요. 애매한 행은 low로 남기세요. JSON만 출력: {"rows":[{"eng":"...","kor":"...","confidence":"high|medium|low"}]}\nSEE:\n${JSON.stringify(see)}`,paired=await gemini(pairPrompt);$('#ocrProgress').style.width='100%';const rows=(paired.rows||see.rows||[]).filter(x=>x.eng||x.kor).map((x,i)=>normalizeWord({id:`ocr-${Date.now()}-${i}`,eng:x.eng,kor:x.kor,confidence:x.confidence||'medium',needsReview:x.confidence==='low'},i));if(!rows.length)throw new Error('단어와 뜻을 찾지 못했어요.');S.ocrDraft={createdAt:nowISO(),quality,rows};save();renderOCRReview(rows,true)}catch(e){toast(`OCR 실패: ${e.message||'다시 시도해 주세요.'}`);renderManualEntry('OCR 결과를 만들지 못했어요. 사진을 다시 찍거나 직접 입력할 수 있습니다.')}
}
async function gemini(prompt,b64,mime){const parts=[{text:prompt}];if(b64)parts.push({inlineData:{mimeType:mime,data:b64}});const model=encodeURIComponent(S.settings.geminiModel||'gemini-2.5-flash'),r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':runtimeApiKey},body:JSON.stringify({contents:[{parts}],generationConfig:{responseMimeType:'application/json'}})});if(!r.ok){if(r.status===401||r.status===403)throw new Error('API 인증을 확인해 주세요.');if(r.status===429)throw new Error('요청이 많아요. 잠시 후 다시 시도해 주세요.');throw new Error(`네트워크/API 오류 ${r.status}`)}const j=await r.json(),txt=j.candidates?.[0]?.content?.parts?.[0]?.text||'{}';return JSON.parse(txt)}
function renderManualEntry(message='단어와 뜻을 직접 입력할 수 있어요.'){renderOCRReview([{id:`manual-${Date.now()}`,eng:'',kor:'',confidence:'manual',needsReview:true}],true,message)}
function renderOCRReview(rows,isDraft=false,message=''){let data=rows.map(normalizeWord);$('#view').innerHTML=`<section class="card"><div class="hero-kicker"><span>REVIEW BEFORE COMMIT</span><span>${data.length}개</span></div><h2>OCR 결과 확인</h2><p>${message||`${data.length}개를 찾았어요. 확인이 필요한 항목만 고치면 됩니다.`}</p><div class="table" id="ocrRows" style="margin-top:12px"></div><div class="btn-row" style="margin-top:13px"><button class="btn secondary" id="addOcrRow" type="button">행 추가</button><button class="btn primary" id="commitSheet" type="button">시험지 만들기</button></div></section>`;const draw=()=>{$('#ocrRows').innerHTML=data.map((w,i)=>`<div class="row" data-i="${i}"><input class="eng" value="${esc(w.eng)}" aria-label="${i+1}번 영어 단어"><input class="kor" value="${esc(w.kor)}" aria-label="${i+1}번 뜻"><span class="badge ${w.needsReview?'weak':'good'}">${w.needsReview?'확인 필요':'확인'}</span><button class="row-delete" data-del="${i}" type="button" aria-label="${i+1}번 행 삭제">×</button></div>`).join('');$$('[data-del]').forEach(b=>b.onclick=()=>{data.splice(Number(b.dataset.del),1);draw()})};draw();$('#addOcrRow').onclick=()=>{data.push(normalizeWord({id:`manual-${Date.now()}`,eng:'',kor:'',confidence:'manual',needsReview:true},data.length));draw()};$('#commitSheet').onclick=()=>{const out=$$('#ocrRows .row').map((r,i)=>normalizeWord({...data[i],eng:$('.eng',r).value.trim(),kor:$('.kor',r).value.trim(),needsReview:false,manuallyEdited:true},i)).filter(x=>x.eng&&x.kor);if(!out.length)return toast('단어와 뜻을 한 개 이상 입력해 주세요.');const newId=isDraft?`sheet-${Date.now()}`:sheet().sheetId,newSheet={sheetId:newId,title:isDraft?`${new Date().toLocaleDateString('ko-KR')} 시험지`:sheet().title,createdAt:isDraft?nowISO():sheet().createdAt,updatedAt:nowISO(),testDate:'',sourceType:isDraft?'photo':'existing',sourceCount:isDraft?1:(sheet().sourceCount||0),status:'READY',caseMastery:0,items:out,recognitionMeta:{reviewedAt:nowISO(),count:out.length}};if(isDraft){S.sheets.unshift(newSheet);S.activeSheetId=newId}else Object.assign(sheet(),newSheet);S.ocrDraft=null;S.learning=clone(DEFAULT_STATE.learning);S.codeRed=clone(DEFAULT_STATE.codeRed);save();toast('사건 파일 작성 완료');currentTab='study';viewStack=[];render()};setPartner('확실한 건 그대로 두고, 애매한 것만 확인하면 돼. 저장 전까지는 Draft야.','note')}
function renderLearningHub(){const ws=validWords();if(!ws.length)return renderSheets();const sh=sheet(),weak=ws.filter(w=>weakScore(w)>0).length;$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">${stateLabel(sh.status)}</span><h2 style="margin:5px 0 0">${esc(sh.title)}</h2></div><div style="text-align:right"><b>${ws.length}단어</b><small style="display:block">취약 ${weak}개</small></div></div><div class="progress" style="margin-top:10px"><span style="width:${learningProgress()}%"></span></div><div class="section-title"><h2>학습 미션</h2><span>보고 → 뜻 → 연결 → 취약 → 검증</span></div><div class="grid2"><button class="mission-card" id="phaseFirst" type="button"><h3>FIRST CONTACT</h3><p>보고, 듣고, 뜻과 철자 형태를 익혀요.</p></button><button class="mission-card" id="phaseMeaning" type="button"><h3>MEANING CHECK</h3><p>영어↔뜻을 양방향 4지선다로 확인해요.</p></button><button class="mission-card" id="phaseConnect" type="button"><h3>CONNECTION</h3><p>단어와 뜻을 빠르게 타일로 연결해요.</p></button><button class="mission-card" id="phaseWeak" type="button"><h3>WEAK WORD</h3><p>오답·PASS·힌트 단어를 더 자주 만나요.</p></button></div><button class="btn danger full" id="phaseCode" style="margin-top:9px" type="button">CODE RED · 전체 철자 최종 검증</button></section>`;$('#phaseFirst').onclick=()=>pushView(renderFirstContact);$('#phaseMeaning').onclick=()=>pushView(renderMeaningCheck);$('#phaseConnect').onclick=()=>pushView(renderConnection);$('#phaseWeak').onclick=()=>pushView(renderWeak);$('#phaseCode').onclick=()=>startCodeRed(false);setPartner('먼저 충분히 익히고, 약한 단어를 더 보고, 마지막에 전체 철자를 확인하자.','default')}
function renderFirstContact(){const ws=validWords(),i=S.learning.firstIndex%ws.length,w=ws[i];sheet().status='LEARNING';S.learning.phase='first';save();$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">FIRST CONTACT</span><h2 style="margin:5px 0 0">신규 단어 습득</h2></div><b>${i+1}/${ws.length}</b></div><div class="progress" style="margin-top:9px"><span style="width:${Math.round((i+1)/ws.length*100)}%"></span></div><section class="card word-card"><div class="eng">${esc(w.eng)}</div><button class="circle-btn" id="speakWord" type="button" style="margin:10px auto 0">발음</button><div class="kor">${esc(w.kor)}</div>${w.example?`<div class="example">${esc(w.example)}</div>`:''}<div class="btn-row" style="margin-top:17px"><button class="btn secondary" id="firstUnsure" type="button">아직 헷갈려</button><button class="btn primary" id="firstNext" type="button">다음 단어</button></div></section></section>`;$('#speakWord').onclick=()=>speakWord(w.eng);$('#firstUnsure').onclick=()=>{w.wrong=(w.wrong||0)+1;advanceFirst(false)};$('#firstNext').onclick=()=>advanceFirst(true);setPartner('지금은 시험이 아니야. 소리와 뜻, 철자 모양을 편하게 연결해둬.','default')}
function advanceFirst(ok){const ws=validWords();markStudy(ok?2:1);S.learning.firstIndex++;if(S.learning.firstIndex>=ws.length){S.learning.firstIndex=0;S.learning.phase='meaning';save();renderMeaningCheck()}else{save();renderFirstContact()}}
function choiceOptions(correct,field){const pool=validWords().filter(x=>x.id!==correct.id);return shuffle([correct,...shuffle(pool).slice(0,3)]).map(x=>({id:x.id,label:field==='kor'?x.kor:x.eng}))}
function renderMeaningCheck(){const ws=validWords(),i=S.learning.meaningIndex%ws.length,w=ws[i],reverse=i%2===1,field=reverse?'eng':'kor',prompt=reverse?w.kor:w.eng,opts=choiceOptions(w,field);S.learning.phase='meaning';sheet().status='LEARNING';save();$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">MEANING CHECK</span><h2 style="margin:5px 0 0">${reverse?'뜻 → 영어':'영어 → 뜻'}</h2></div><b>${i+1}/${ws.length}</b></div><section class="card word-card"><div class="eng" style="font-size:${reverse?'23px':'31px'}">${esc(prompt)}</div><div class="choice-grid">${opts.map(o=>`<button class="choice" data-choice="${esc(o.id)}" type="button">${esc(o.label)}</button>`).join('')}</div></section></section>`;$$('[data-choice]').forEach(b=>b.onclick=()=>meaningAnswer(b,w,b.dataset.choice===w.id));setPartner('정답을 외워 찍기보다, 영어와 뜻의 연결을 빠르게 확인해보자.','focus')}
function meaningAnswer(btn,w,ok){$$('[data-choice]').forEach(b=>b.disabled=true);btn.classList.add(ok?'correct':'wrong');if(!ok){w.wrong=(w.wrong||0)+1;setPartner('이 단어는 추적 목록에 넣어둘게. 뒤에서 더 자주 만나자.','note')}else{S.learning.combo++;S.learning.flow=Math.min(6,S.learning.flow+1)}S.learning.history.push({at:nowISO(),mode:'meaning',wordId:w.id,result:ok?'CORRECT':'WRONG'});markStudy(ok?3:1);setTimeout(()=>{S.learning.meaningIndex++;if(S.learning.meaningIndex>=validWords().length){S.learning.meaningIndex=0;S.learning.phase='connection';save();renderConnection()}else{save();if(ok&&S.learning.combo>0&&S.learning.combo%5===0)triggerFever(()=>renderMeaningCheck());else renderMeaningCheck()}},350)}
function connectionSet(){const ordered=[...validWords()].sort((a,b)=>weakScore(b)-weakScore(a));const start=(S.learning.connectionRound*4)%ordered.length,chosen=[];for(let i=0;i<Math.min(4,ordered.length);i++)chosen.push(ordered[(start+i)%ordered.length]);return chosen}
function renderConnection(){const set=connectionSet();selectedTile=null;S.learning.phase='connection';save();const left=shuffle(set),right=shuffle(set);$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">CONNECTION</span><h2 style="margin:5px 0 0">단어와 뜻 연결</h2></div><b>Round ${S.learning.connectionRound+1}</b></div><section class="card"><p>왼쪽 영어 하나와 오른쪽 뜻 하나를 차례로 선택하세요.</p><div class="tile-board"><div>${left.map(w=>`<button class="tile tile-eng" data-id="${w.id}" data-side="eng" type="button">${esc(w.eng)}</button>`).join('')}</div><div>${right.map(w=>`<button class="tile tile-kor" data-id="${w.id}" data-side="kor" type="button">${esc(w.kor)}</button>`).join('')}</div></div><button class="btn primary full" id="connectionNext" style="margin-top:12px" type="button" disabled>다음 라운드</button></section></section>`;$$('.tile').forEach(b=>b.onclick=()=>tilePick(b));setPartner('이번엔 단어와 뜻을 빠르게 연결해보자. 틀려도 바로 다음 단서로 가면 돼.','play')}
function tilePick(btn){if(btn.classList.contains('matched'))return;if(!selectedTile){selectedTile=btn;btn.classList.add('selected');return}if(selectedTile.dataset.side===btn.dataset.side){selectedTile.classList.remove('selected');selectedTile=btn;btn.classList.add('selected');return}const ok=selectedTile.dataset.id===btn.dataset.id,id=btn.dataset.id;if(ok){$$(`.tile[data-id="${id}"]`).forEach(x=>x.classList.add('matched'));S.learning.combo++;S.learning.flow=Math.min(6,S.learning.flow+1);markStudy(2)}else{const w=validWords().find(x=>x.id===selectedTile.dataset.id);if(w)w.wrong=(w.wrong||0)+1;markStudy(1);setPartner('연결이 살짝 엇갈렸네. 두 단서를 다시 보고 이어가자.','think')}selectedTile.classList.remove('selected');selectedTile=null;if($$('.tile:not(.matched)').length===0){$('#connectionNext').disabled=false;$('#connectionNext').onclick=()=>{S.learning.connectionRound++;if(S.learning.connectionRound>=Math.ceil(validWords().length/4)){S.learning.connectionRound=0;S.learning.phase='weak';save();renderWeak()}else{save();renderConnection()}}}}
function renderWeak(){const ordered=[...validWords()].sort((a,b)=>weakScore(b)-weakScore(a)),weak=ordered.filter(w=>weakScore(w)>0),top=(weak.length?weak:ordered).slice(0,Math.min(6,ordered.length));S.learning.phase='weak';save();$('#view').innerHTML=`<section class="learning-shell"><div class="learn-head"><div><span class="phase-chip">WEAK WORD PRIORITY</span><h2 style="margin:5px 0 0">어려운 단어 집중</h2></div><b>${top.length}개</b></div><section class="card"><div class="flow-gauge">${[0,1,2,3,4,5].map(i=>`<i class="${i<S.learning.flow?'on':''}"></i>`).join('')}</div><div class="weak-list" style="margin-top:13px">${top.map(w=>`<div class="weak-item"><div><b>${esc(w.eng)}</b><div style="font-size:10px;color:#66736a">${esc(w.kor)}</div></div><span class="badge ${weakScore(w)>=8?'weak':'mid'}">${weakScore(w)>=8?'집중':'확인'}</span></div>`).join('')}</div><div class="btn-row" style="margin-top:13px"><button class="btn secondary" id="weakReplay" type="button">취약 단어 다시 보기</button><button class="btn danger" id="weakToCode" type="button">CODE RED</button></div></section></section>`;$('#weakReplay').onclick=()=>{const first=top[0];S.learning.firstIndex=Math.max(0,validWords().findIndex(w=>w.id===first.id));save();renderFirstContact()};$('#weakToCode').onclick=()=>startCodeRed(false);setPartner('약한 단어에 시간을 더 쓰되, 전체 단어를 마지막 CODE RED에서 전부 확인할게.','focus')}
function triggerFever(next){S.learning.fever=true;save();$('#view').innerHTML=`<section class="card fever-stage"><div class="food-rain"><i class="food" style="left:8%">PIZZA</i><i class="food">DONUT</i><i class="food">JUICE</i><i class="food">BURGER</i><i class="food">FRUIT</i></div><div style="position:relative;z-index:2;text-align:center;padding-top:54px"><h1 style="font-size:35px;margin:0;color:#4d783e">FEVER TIME</h1><p>연속 성공 보너스 · 학습 판정은 그대로</p><div class="flow-gauge" style="max-width:290px;margin:17px auto">${[0,1,2,3,4,5].map(()=>'<i class="on"></i>').join('')}</div><button class="btn primary" id="leaveFever" type="button">계속 학습</button></div></section>`;setPartner('흐름 좋네. 잠깐 축제다. 문제는 그대로 차분하게 가자.','fever',true);$('#leaveFever').onclick=()=>{S.learning.fever=false;S.learning.flow=0;save();next()}}
function blankCount(word){const n=word.length;return n<=5?Math.min(2,Math.max(1,n-2)):n<=8?3:Math.min(4,n-2)}
function makeCodeSession(w){const n=blankCount(w.eng),idx=shuffle([...w.eng].map((_,i)=>i)).slice(0,n).sort((a,b)=>a-b),real=idx.map((i,k)=>({id:`r${k}-${Math.random()}`,ch:w.eng[i].toLowerCase(),real:true})),required=new Set(real.map(x=>x.ch)),alphabet='abcdefghijklmnopqrstuvwxyz',fakes=[];while(fakes.length<Math.max(3,n)){const ch=alphabet[Math.floor(Math.random()*alphabet.length)];if(!required.has(ch))fakes.push({id:`f${fakes.length}-${Math.random()}`,ch,real:false})}return {word:w,blankIdx:idx,keys:shuffle([...real,...fakes]),answers:{},hintLevel:0,wrongAttempts:0,seconds:S.settings.pressureReduced?24:(w.eng.length<=5?15:w.eng.length<=8?18:21),start:Date.now()}}
function codeTargets(){const ws=validWords();if(S.codeRed.retryOnly){const set=new Set(S.codeRed.targetIds.length?S.codeRed.targetIds:S.codeRed.retrace);return ws.filter(w=>set.has(w.id))}return ws}
function startCodeRed(retryOnly=false){stopCodeTimer();const targets=retryOnly?validWords().filter(w=>S.codeRed.retrace.includes(w.id)):validWords();if(!targets.length)return toast('CODE RED 대상 단어가 없어요.');S.learning.phase='code';sheet().status='CODE_RED_READY';S.codeRed.index=0;S.codeRed.retryOnly=retryOnly;S.codeRed.targetIds=targets.map(w=>w.id);if(!retryOnly){S.codeRed.results={};S.codeRed.retrace=[]}save();viewStack=[];renderCodeRed()}
function renderCodeRed(){const targets=codeTargets();if(S.codeRed.index>=targets.length)return finishCodeRed();const w=targets[S.codeRed.index];codeSession=makeCodeSession(w);selectedKey=null;const letters=[...w.eng].map((ch,i)=>codeSession.blankIdx.includes(i)?`<span class="slot-anchor">_</span>`:esc(ch)).join('');$('#view').innerHTML=`<section class="code-shell"><div class="code-head"><div><span class="code-label">CODE RED</span><div class="code-instruction" style="margin-top:6px">${S.codeRed.retryOnly?'RE-CHECK':'ALL CURRENT WORDS'} · ${S.codeRed.index+1}/${targets.length}</div></div><div id="timeRing" class="time-ring" style="--p:100"><b><span id="timeText">${codeSession.seconds}</span>s</b></div></div><div class="code-word"><div>${letters}</div><div class="slots">${codeSession.blankIdx.map((_,n)=>`<button class="slot" data-slot="${n}" type="button" aria-label="${n+1}번째 빈칸"></button>`).join('')}</div></div><p class="code-instruction">Letter Key를 빈칸으로 끌거나, Key를 탭한 뒤 Slot을 탭하세요.</p><div class="key-tray">${codeSession.keys.map(k=>`<button draggable="true" class="letter-key" data-key="${k.id}" type="button">${esc(k.ch)}</button>`).join('')}</div><div class="btn-row"><button class="btn gold" id="codeHint" type="button">힌트</button><button class="btn secondary" id="undoCode" type="button">되돌리기</button><button class="btn danger" id="passCode" type="button">PASS</button></div></section>`;bindCodeRed();startCodeTimer();setPartner('진짜 철자 열쇠만 골라. 가짜도 섞여 있어.','radio')}
function bindCodeRed(){$$('.letter-key').forEach(k=>{k.onclick=()=>selectKey(k.dataset.key);k.addEventListener('dragstart',e=>e.dataTransfer.setData('text/plain',k.dataset.key))});$$('.slot').forEach(s=>{s.onclick=()=>placeSelected(Number(s.dataset.slot));s.addEventListener('dragover',e=>e.preventDefault());s.addEventListener('drop',e=>{e.preventDefault();placeKey(e.dataTransfer.getData('text/plain'),Number(s.dataset.slot))})});$('#undoCode').onclick=undoCode;$('#codeHint').onclick=useCodeHint;$('#passCode').onclick=()=>recordCodeResult('PASS')}
function selectKey(id){selectedKey=id;$$('.letter-key').forEach(k=>k.classList.toggle('selected',k.dataset.key===id))}
function placeSelected(slot){if(selectedKey)placeKey(selectedKey,slot)}
function placeKey(keyId,slot){const key=codeSession.keys.find(k=>k.id===keyId);if(!key||key.used)return;const need=codeSession.word.eng[codeSession.blankIdx[slot]].toLowerCase();if(key.ch!==need){codeSession.wrongAttempts++;selectedKey=null;$$('.letter-key').forEach(k=>k.classList.remove('selected'));const el=$(`[data-key="${CSS.escape(keyId)}"]`);if(el){el.classList.remove('reject');void el.offsetWidth;el.classList.add('reject')}setPartner('가짜 열쇠였네. 원래 자리로 돌려둘게.','focus');return}const prev=codeSession.answers[slot];if(prev){const pk=codeSession.keys.find(k=>k.id===prev);if(pk)pk.used=false}codeSession.answers[slot]=key.id;key.used=true;selectedKey=null;updateCodeUI();if(Object.keys(codeSession.answers).length===codeSession.blankIdx.length)setTimeout(checkCodeAnswer,180)}
function updateCodeUI(){$$('.slot').forEach(s=>{const id=codeSession.answers[Number(s.dataset.slot)],key=codeSession.keys.find(k=>k.id===id);s.textContent=key?.ch||'';s.classList.toggle('filled',!!key)});$$('.letter-key').forEach(el=>{const key=codeSession.keys.find(x=>x.id===el.dataset.key);el.classList.toggle('used',!!key?.used);el.classList.remove('selected')})}
function undoCode(){const slots=Object.keys(codeSession.answers);if(!slots.length)return;const last=slots.at(-1),id=codeSession.answers[last],k=codeSession.keys.find(x=>x.id===id);if(k)k.used=false;delete codeSession.answers[last];updateCodeUI()}
function useCodeHint(){codeSession.hintLevel++;const unanswered=codeSession.blankIdx.map((_,i)=>i).filter(i=>!codeSession.answers[i]);if(!unanswered.length)return;const slot=unanswered[0],needed=codeSession.word.eng[codeSession.blankIdx[slot]].toLowerCase(),key=codeSession.keys.find(k=>!k.used&&k.ch===needed);if(!key)return;if(codeSession.hintLevel>=3)placeKey(key.id,slot);else{const el=$(`[data-key="${CSS.escape(key.id)}"]`);el?.classList.add('selected');setPartner(codeSession.hintLevel===1?'필요한 열쇠 하나가 살짝 반응했어.':'정답 열쇠를 빈칸 가까이 생각해봐.','hint')}}
function checkCodeAnswer(){const built=codeSession.blankIdx.map((_,slot)=>codeSession.keys.find(k=>k.id===codeSession.answers[slot])?.ch||''),need=codeSession.blankIdx.map(i=>codeSession.word.eng[i].toLowerCase());if(built.every((x,i)=>x===need[i]))recordCodeResult(codeSession.wrongAttempts>0?'WRONG':codeSession.hintLevel?'HINT_USED':'CORRECT')}
function recordCodeResult(type){stopCodeTimer();const w=codeSession.word,attempt={wordId:w.id,type,at:nowISO(),hintLevel:codeSession.hintLevel,wrongAttempts:codeSession.wrongAttempts};S.codeRed.results[w.id]=attempt;S.codeRed.history.push(attempt);w.learningStats=w.learningStats||{};w.learningStats.codeRedAttempts=(w.learningStats.codeRedAttempts||0)+1;if(['WRONG','PASS','TIMEOUT','HINT_USED'].includes(type)){if(!S.codeRed.retrace.includes(w.id))S.codeRed.retrace.push(w.id);if(type==='WRONG')w.wrong=(w.wrong||0)+1;if(type==='PASS')w.pass=(w.pass||0)+1;if(type==='TIMEOUT')w.learningStats.timeout=(w.learningStats.timeout||0)+1;if(type==='HINT_USED')w.hint=(w.hint||0)+1}else{S.learning.combo++;S.learning.flow=Math.min(6,S.learning.flow+1)}S.codeRed.index++;markStudy(type==='CORRECT'?5:1);save();if(S.codeRed.index<codeTargets().length)renderCodeRed();else finishCodeRed()}
function startCodeTimer(){const total=codeSession.seconds;codeTimer=setInterval(()=>{const left=Math.max(0,total-(Date.now()-codeSession.start)/1000),pct=Math.round(left/total*100),ring=$('#timeRing'),txt=$('#timeText');if(!ring||!txt)return;ring.style.setProperty('--p',pct);txt.textContent=Math.ceil(left);ring.classList.toggle('warn',pct<=45&&pct>20);ring.classList.toggle('alert',pct<=20);if(left<=0)recordCodeResult('TIMEOUT')},150)}
function stopCodeTimer(){if(codeTimer){clearInterval(codeTimer);codeTimer=null}}
function finishCodeRed(){stopCodeTimer();const currentTargets=codeTargets(),passed=currentTargets.filter(w=>S.codeRed.results[w.id]?.type==='CORRECT').map(w=>w.id);if(S.codeRed.retryOnly)S.codeRed.retrace=S.codeRed.retrace.filter(id=>!passed.includes(id));if(S.codeRed.retrace.length){sheet().status='RETRACE_REQUIRED';save();return renderRetrace()}sheet().caseMastery=100;sheet().status='TEST_READY';S.learning.phase='done';save();renderComplete()}
function renderRetrace(){const targets=validWords().filter(w=>S.codeRed.retrace.includes(w.id));$('#view').innerHTML=`<div class="section-title"><h2>RETRACE</h2><span>Fail → Learn Again → Recall Again</span></div><section class="card tint-leaf"><p>틀린 직후 같은 정답을 즉시 반복하지 않습니다. 뜻·발음·철자를 짧게 다시 본 뒤 해당 단어만 재검증합니다.</p><div class="retrace-list" style="margin-top:13px">${targets.map(w=>`<div class="retrace-item"><div><b>${esc(w.eng)}</b><span>${esc(w.kor)}</span></div><button class="circle-btn speak-retrace" data-word="${esc(w.eng)}" type="button">듣기</button></div>`).join('')}</div><button class="btn danger full" id="retryCode" style="margin-top:13px" type="button">이 단어만 다시 CODE RED</button></section>`;$$('.speak-retrace').forEach(b=>b.onclick=()=>speakWord(b.dataset.word));$('#retryCode').onclick=()=>startCodeRed(true);setPartner('놓쳤다고 끝난 건 아니지. 다시 익힌 뒤 같은 단어만 재검증하자.','note')}
function renderComplete(){const old=validWords()[0];$('#view').innerHTML=`<section class="card tint-leaf" style="text-align:center;padding:25px"><img src="${guideAsset('cheer')}" alt="" style="width:110px;height:110px;object-fit:contain;margin:0 auto 4px"><h1 style="margin:0">사건 준비 완료</h1><p>현재 시험지의 유효 단어를 CODE RED와 RETRACE까지 확인했어요.</p><div class="grid3" style="margin-top:14px"><div class="status-pill"><b>100%</b><span>Case Mastery</span></div><div class="status-pill"><b>${S.xp}</b><span>XP</span></div><div class="status-pill"><b>${memoryStrength()}%</b><span>Memory</span></div></div><button class="btn primary full" id="backHome" style="margin-top:14px" type="button">홈으로</button></section>${old?`<div class="section-title"><h2>작은 과거 사건</h2><span>선택적 장기기억 이벤트</span></div><section class="card memory-event"><p>학습 흐름을 막지 않는 작은 확인이야. 건너뛰어도 불이익은 없어.</p><div class="bigword">${esc(old.eng)}</div><p style="text-align:center">${esc(old.kor)}</p><div class="btn-row" style="margin-top:12px"><button class="btn secondary" id="memorySkip" type="button">건너뛰기</button><button class="btn secondary" id="memoryNo" type="button">기억 안 나요</button><button class="btn primary" id="memoryYes" type="button">기억해요</button></div></section>`:''}`;$('#backHome').onclick=()=>{currentTab='home';viewStack=[];render()};if(old){$('#memorySkip').onclick=()=>toast('현재 사건 기록에는 영향이 없어요.');$('#memoryYes').onclick=()=>{S.memory[old.id]={last:nowISO(),strength:Math.min(100,(S.memory[old.id]?.strength||60)+10)};save();toast('기억 기록 이상 없음')};$('#memoryNo').onclick=()=>{S.memory[old.id]={last:nowISO(),strength:Math.max(10,(S.memory[old.id]?.strength||60)-15)};save();toast('다음 복습 우선도를 조금 올렸어요.')}}setPartner('사건 종결. 오늘 범위는 여기까지 확보했어.','cheer',true)}
function renderWords(){const ws=validWords();$('#view').innerHTML=`<div class="section-title"><h2>내 단어장</h2><span>${ws.length}개</span></div><section class="card">${ws.length?`<div class="weak-list">${[...ws].sort((a,b)=>weakScore(b)-weakScore(a)).map(w=>`<div class="weak-item"><div><b>${esc(w.eng)}</b><div style="font-size:10px;color:#66736a">${esc(w.kor)}</div></div><span class="badge ${weakScore(w)>=8?'weak':weakScore(w)>0?'mid':'good'}">${weakScore(w)>=8?'약함':weakScore(w)>0?'확인':'안정'}</span></div>`).join('')}</div>`:'<p>아직 단어가 없어요.</p>'}</section>`;setPartner('단어장은 지난 사건의 기록이야. 현재 시험지보다 앞서지는 않아.','note')}
function renderRecords(){const sh=sheet();$('#view').innerHTML=`<div class="section-title"><h2>기록</h2><span>Case ≠ Memory</span></div><section class="card tint-sky"><div class="metric"><span>Case Mastery</span><b>${sh.caseMastery||0}%</b></div><div class="metric"><span>Memory Strength</span><b>${memoryStrength()}%</b></div><div class="metric"><span>총 XP</span><b>${S.xp}</b></div><div class="metric"><span>연속 학습</span><b>${S.streak}일</b></div></section><div class="section-title"><h2>최근 학습</h2><span>${APP_REV}</span></div><section class="card">${S.sessions.length?S.sessions.slice(-7).reverse().map(x=>`<div class="metric"><span>${esc(x.date)}</span><b>${x.count}회</b></div>`).join(''):'<p>아직 기록이 없어요.</p>'}</section>`;setPartner('완료한 사건은 완료 상태 그대로야. 장기 기억은 따로 천천히 추적할게.','default')}
function exportData(){const copy=clone(S);delete copy.settings.geminiKey;const blob=new Blob([JSON.stringify(copy,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ZPD_WORD_DATA_${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importData(file){try{const data=JSON.parse(await file.text()),m=migrate(data);if(!Array.isArray(m.sheets)||!m.sheets.length)throw new Error('시험지 데이터가 없어요.');S=m;save();toast('데이터를 불러왔어요.');$('#modalRoot').innerHTML='';render()}catch(e){toast(`불러오기 실패: ${e.message||'파일을 확인해 주세요.'}`)}}
function openSettings(){$('#modalRoot').innerHTML=`<div class="modal-back"><section class="modal"><div class="section-title"><h2>설정</h2><button class="circle-btn" id="closeSettings" type="button">닫기</button></div><div class="setting"><div><label>길잡이 음성</label><small>영어 단어 발음보다 우선하지 않습니다.</small></div><button class="switch ${S.settings.partnerVoice?'on':''}" data-toggle="partnerVoice" type="button"><i></i></button></div><div class="setting"><div><label>Reduced Motion</label><small>과한 움직임을 줄입니다.</small></div><button class="switch ${S.settings.reducedMotion?'on':''}" data-toggle="reducedMotion" type="button"><i></i></button></div><div class="setting"><div><label>긴장 연출 줄이기</label><small>CODE RED 시간을 조금 넉넉하게 제공합니다.</small></div><button class="switch ${S.settings.pressureReduced?'on':''}" data-toggle="pressureReduced" type="button"><i></i></button></div><div class="setting"><div style="width:100%"><label>Gemini API Key</label><small>개인 테스트용 · 이번 브라우저 세션에만 보관. 공개 배포는 서버 프록시 권장.</small><input id="apiKey" class="input" type="password" value="${esc(runtimeApiKey)}" placeholder="API Key"></div></div><div class="setting"><div style="width:100%"><label>Gemini Model</label><input id="apiModel" class="input" value="${esc(S.settings.geminiModel)}"></div></div><div class="btn-row" style="margin-top:13px"><button class="btn secondary" id="exportData" type="button">데이터 내보내기</button><button class="btn secondary" id="importData" type="button">데이터 불러오기</button></div><button class="btn primary full" id="saveSettings" style="margin-top:8px" type="button">설정 저장</button><button class="btn secondary full" id="restartOnboarding" style="margin-top:8px" type="button">프로필/길잡이 다시 설정</button><p style="margin-top:10px">Build ${APP_REV} · Schema ${SCHEMA_VERSION}</p></section></div>`;$('#closeSettings').onclick=()=>$('#modalRoot').innerHTML='';$$('[data-toggle]').forEach(b=>b.onclick=()=>{const k=b.dataset.toggle;S.settings[k]=!S.settings[k];b.classList.toggle('on',S.settings[k]);save()});$('#saveSettings').onclick=()=>{runtimeApiKey=$('#apiKey').value.trim();sessionStorage.setItem('zpd_runtime_api_key',runtimeApiKey);S.settings.geminiModel=$('#apiModel').value.trim()||'gemini-2.5-flash';save();$('#modalRoot').innerHTML='';toast('설정을 저장했어요. API Key는 세션에만 유지됩니다.')};$('#restartOnboarding').onclick=()=>{S.onboardingDone=false;S.onboardingStep=0;save();$('#modalRoot').innerHTML='';render()};$('#exportData').onclick=exportData;$('#importData').onclick=()=>$('#importDataInput').click()}
$('#settingsBtn').onclick=openSettings;$('#backBtn').onclick=goBack;$('#partnerVoiceBtn').onclick=()=>partnerSpeak();$('#profileCameraInput').addEventListener('change',e=>profilePicked(e.target.files[0]));$('#profileLibraryInput').addEventListener('change',e=>profilePicked(e.target.files[0]));$('#sheetCameraInput').addEventListener('change',e=>sheetPicked(e.target.files[0]));$('#sheetLibraryInput').addEventListener('change',e=>sheetPicked(e.target.files[0]));$('#importDataInput').addEventListener('change',e=>importData(e.target.files[0]));$$('.nav-btn').forEach(b=>b.onclick=()=>{viewStack=[];stopCodeTimer();currentTab=b.dataset.tab;render()});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));save();render();
